name: laravel_auth_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6  
  carousel_slider: 4.2.0
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.jpeg
    - assets/images/Global-Card.jpg
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/slider3.jpg
    - assets/images/mrm.jpg
    - assets/images/logo.jpg
    - assets/images/mslogo.png
    - assets/images/yuva.png
    - assets/images/vihar_seva.jpg
    - assets/logo.png
    - assets/logo.ico
    - assets/logo_11zon.png

# ✅ Splash Screen Configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.jpeg
  android: true
  ios: true
  android_gravity: center

# ✅ App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
