name: laravel_auth_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.14.0+14

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0  
  http: ^1.5.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6  
  carousel_slider: ^5.1.1
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  confetti: ^0.8.0
  webview_flutter: ^4.13.0 
  image: ^4.1.7
  widget_to_image: ^2.0.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  awesome_dialog: ^3.2.1
  google_fonts: ^6.3.1 
  pdfx: ^2.9.2
  flutter_linkify: ^6.0.0
  flutter_staggered_animations: ^1.1.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1
  


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.jpeg
    - assets/images/Global-Card.jpg
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/slider3.jpg
    - assets/images/mrm.jpg
    - assets/images/logo.jpg
    - assets/images/mslogo.png
    - assets/images/yuva.png
    - assets/images/vihar_seva.jpg
    - assets/images/spf.jpg
    - assets/logo.png
    - assets/logo.ico
    - assets/logo_11zon.png
    - assets/images/card_template.jpeg
    - assets/images/nanesh-chiktsalay.jpg
    - assets/images/daanpeti-logo.jpg
    - assets/images/idam_namam.jpg
    - assets/images/donation.webp
    - assets/images/donor_portal_qr.png
    - assets/images/kesariya-karyshala.JPG
    - assets/images/parivar.JPG
    - assets/images/yuwati-shakti.JPG
    - assets/images/sangthan-150x150.JPG
    - assets/images/woman_forms.JPG
    - assets/images/sarvdharmi.JPG
    - assets/images/scholarshtip.JPG
    - assets/images/golden_steps.JPEG
    - assets/images/yuva_parichay.jpeg
    - assets/images/yuva-r.png
    -  assets/11zon_resized.png
    - assets/pdf/vivarnika.pdf
    - assets/images/sbinew.JPG

# ✅ Splash Screen Configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true
  android_gravity: center

# ✅ App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
