name: laravel_auth_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2  
  http: ^0.13.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6  
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.10
  intl: ^0.18.1
  confetti: ^0.7.0
  webview_flutter: ^4.7.0 
  image: ^4.1.7
  widget_to_image: ^2.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.1
  qr_flutter: ^4.1.0
  pdf: ^3.10.6
  printing: ^5.12.0
  awesome_dialog: ^3.0.2
  google_fonts: ^4.0.4 
  pdfx: ^2.0.3
  flutter_linkify: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo1.jpeg
    - assets/images/Global-Card.jpg
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/slider3.jpg
    - assets/images/mrm.jpg
    - assets/images/logo.jpg
    - assets/images/mslogo.png
    - assets/images/yuva.png
    - assets/images/vihar_seva.jpg
    - assets/logo.png
    - assets/logo.ico
    - assets/logo_11zon.png
    - assets/images/card_template.jpeg
    - assets/images/nanesh-chiktsalay.jpg
    - assets/images/daanpeti-logo.jpg
    - assets/images/idam_namam.jpg
    - assets/images/donation.webp
    - assets/images/donor_portal_qr.png
    - assets/images/kesariya-karyshala.JPG
    - assets/images/parivar.JPG
    - assets/images/yuwati-shakti.JPG
    - assets/images/sangthan-150x150.JPG
    - assets/images/woman_forms.JPG
    - assets/images/sarvdharmi.JPG
    - assets/images/scholarshtip.JPG
    - assets/images/golden_steps.JPEG
    - assets/images/yuva_parichay.jpeg
    - assets/images/yuva-r.png

# ✅ Splash Screen Configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.jpeg
  android: true
  ios: true
  android_gravity: center

# ✅ App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"
